Deal damage only to agents not cowering
SOMAS2022/SOMAS2022 pull request #62
Opened 2022-11-20 22:10 UTC by Razvan00Rusu

A quick fix to #55 to only deal damage to agents not cowering. 

This raises an issue where we now need to implement an upper level of rounds per level to ensure that agents can't all cower indefinitely to take no damage.

2022-11-20 22:11 UTC, BusterBlack commented
if all agents cower... then they take all the damage. So that should never happen

2022-11-20 22:12 UTC, Razvan00Rusu commented
> if all agents cower... then they take all the damage. So that should never happen

Wait what I thought only non-cowering agents took damage : ( - 1 sec let me fix

2022-11-20 22:13 UTC, BusterBlack commented
no no.... the number of agents cowering = total number of agents. Then all take damage.
if not... only people who fight take damage

2022-11-20 22:15 UTC, Razvan00Rusu commented
> no no.... the number of agents cowering = total number of agents. Then all take damage. if not... only people who fight take damage

Ok should be good now I think

2022-11-20 22:47 UTC, neeldug requested changes
Probably should finally get around to wrapping all of these arrays into a struct  to avoid multiple returns and binds and retyping them to `commons.ID`.

2022-11-21 01:34 UTC, neeldug approved these changes
LGTM

2022-11-21 01:40 UTC, merged