Team1 - Initial implementation of client
SOMAS2022/SOMAS2022 pull request #66
Opened 2022-11-22 11:40 UTC by EdvardJSHolen

2022-11-22 17:12 UTC, neeldug commented
Rebased to avoid merge commit.

2022-11-22 17:17 UTC, neeldug requested changes

2022-11-22 17:17 UTC, neeldug commented on pkg/infra/.env
> +AGENT_TEAM1_QUANTITY=100
```suggestion
AGENT_TEAM1_QUANTITY=100

```

2022-11-22 17:17 UTC, neeldug commented on pkg/infra/game/agent/team1.go
> +}
Perhaps move to a helpers module?

2022-11-22 17:17 UTC, neeldug commented on pkg/infra/go.sum
> +github.com/google/go-cmp v0.5.5/go.mod h1:v8dTdLbMG2kIc/vJvl+f65V22dbkXbowE6jgT/gNBxE=
```suggestion
```

2022-11-22 17:17 UTC, neeldug commented on pkg/infra/go.sum
> +google.golang.org/protobuf v1.28.1/go.mod h1:HV8QOd/L58Z+nl8r43ehVNZIU/HEI6OcFqwMG9pJV4I=
```suggestion
```

2022-11-22 17:17 UTC, neeldug commented on pkg/infra/main_test.go
> +func TestMain(m *testing.M) {
This is unused as of now, main testing requires more tests to be provided in separate functions that will use main test body as closures.

2022-11-27 15:18 UTC, sherwin-dc commented
After attempting to rebase on main there are errors in the following lines, because `view.AgentState()` behaves differently and does not return a pointer anymore. Does anyone know what this should be changed to?

```go
       // Ensure that socialCapital map is initialised
	if len(r.socialCapital) == 0 && view.AgentState().Len() > 1 {
```

```go
		// Populate map with every currently living agent, and calculate socialCapital based on log
		itr := view.AgentState().Iterator()
```

2022-11-28 12:49 UTC, neeldug commented
> After attempting to rebase on main there are errors in the following lines, because `view.AgentState()` behaves differently and does not return a pointer anymore. Does anyone know what this should be changed to?
> 
> ```go
>        // Ensure that socialCapital map is initialised
> 	if len(r.socialCapital) == 0 && view.AgentState().Len() > 1 {
> ```
> 
>  ```go
> 		// Populate map with every currently living agent, and calculate socialCapital based on log
> 		itr := view.AgentState().Iterator()
> ```

Similar to what @Razvan00Rusu said if you just add this line and refer to the variable it should work identically:

```go
agentState := v.AgentState()
```

2022-11-28 13:02 UTC, sherwin-dc commented
It seems your suggestions have worked. I have fixed this in #73

2022-12-04 20:17 UTC, neeldug commented
Closed in favour of #73

2022-12-04 20:17 UTC, closed without merging