[Infra] Specialise Initialisation functions for team experiments
SOMAS2022/SOMAS2022 pull request #69
Opened 2022-11-23 18:57 UTC by sherwin-dc

- Teams can now create their own agent map within their team files for
    experimentation.
- Refactor initialise code out of main
- Added an example probabilistic agent in team0 files

2022-11-23 19:26 UTC, 0x6770 commented
I thought we have already enabled customisable agent map via #25?

2022-11-23 19:30 UTC, neeldug commented
> I thought we have already enabled customisable agent map via #25?

I thought so too…

2022-11-23 19:37 UTC, sherwin-dc commented
This has nothing to do with mixing different agent types. This PR allows for the agent map to be kept in another file eg `infra/teams/team0/init.go`, otherwise each team would be keeping a local copy of the whole repo with their own agent map in `main.go`

2022-11-23 19:43 UTC, 0x6770 commented
> This has nothing to do with mixing different agent types. This PR allows for the agent map to be kept in another file eg `infra/teams/team0/init.go`, otherwise each team would be keeping a local copy of the whole repo with their own agent map in `main.go`

oh I see, if you want to add a way to allow teams/members to save their agent map somewhere, I would suggest to add a flag to config `env` path. By this way, we don't need to modify the existing code, but only add one line in `main.go`

2022-11-23 19:58 UTC, 0x6770 commented
Something like this
```
diff --git a/pkg/infra/main.go b/pkg/infra/main.go
index 27badf4..e6bc282 100644
--- a/pkg/infra/main.go
+++ b/pkg/infra/main.go
@@ -35,11 +35,12 @@ func main() {
        // define flags
        useJSONFormatter := flag.Bool("j", false, "Whether to output logs in JSON")
        debug := flag.Bool("d", false, "Whether to run in debug mode. If false, only logs with level info or above will be shown")
+       envFile := flag.String("c", ".env", "Path to environment file, default to .env")
        flag.Parse()

        logging.InitLogger(*useJSONFormatter, *debug)

-       agentMap, globalState, gameConfig := initialise()
+       agentMap, globalState, gameConfig := initialise(*envFile)
        gameLoop(globalState, agentMap, gameConfig)
 }

@@ -110,11 +111,11 @@ func gameLoop(globalState state.State, agentMap map[commons.ID]agent.Agent, game
        logging.Log(logging.Info, nil, fmt.Sprintf("Congratulations, The Peasants have escaped the pit with %d remaining.", len(agentMap)))
 }

-func initialise() (map[commons.ID]agent.Agent, state.State, config.GameConfig) {
+func initialise(envFile string) (map[commons.ID]agent.Agent, state.State, config.GameConfig) {
        agentMap := make(map[commons.ID]agent.Agent)
        agentStateMap := make(map[commons.ID]state.AgentState)

-       err := godotenv.Load()
+       err := godotenv.Load(envFile)
        if err != nil {
                logging.Log(logging.Error, nil, "No .env file located, using defaults")
        }
```

2022-11-23 21:15 UTC, neeldug commented
> > This has nothing to do with mixing different agent types. This PR allows for the agent map to be kept in another file eg `infra/teams/team0/init.go`, otherwise each team would be keeping a local copy of the whole repo with their own agent map in `main.go`
> 
> oh I see, if you want to add a way to allow teams/members to save their agent map somewhere, I would suggest to add a flag to config `env` path. By this way, we don't need to modify the existing code, but only add one line in `main.go`

Yep I agree with this — since in reality the env files enable full customisability.

2022-11-23 21:27 UTC, sherwin-dc commented
Yes that does seem simpler, but do you know how to load string values into a map to fit its types? If we have a map of `string` to `string` it would be easy to load values from a json file and I can find examples online, but in this case how would we load text into a map of `string` to `agent.Strategy` func?

Lets say the json/env file contains something like
```
	"RANDOM":          agent.NewRandomAgent(),
	"AggressiveAgent": NewProbabilisticAgent(0.1, 0.8, 0.1),
	"CowardlyAgent":   NewProbabilisticAgent(0.9, 0.05, 0.05),
```

2022-11-23 21:41 UTC, 0x6770 commented
```
# in .env_team0
MODE=default
LEVELS=60
STARTING_HP=1000
STARTING_ATTACK=20
STARTING_SHIELD=20
BASE_STAMINA=2000
THRESHOLD_PCT=0.6
AGENT_RANDOM_QUANTITY=100
AGENT_AggressiveAgent_QUANTITY=20
AGENT_CowardlyAgent_QUANTITY=20
```

```go
// in team0_agent.go
func NewAggressiveAgent() = NewProbabilisticAgent(0.1, 0.8, 0.1)
func NewCowardlyAgent() = NewProbabilisticAgent(0.9, 0.05, 0.05)
```

```go
// in main.go
var InitAgentMap = map[commons.ID]agent.Strategy{
	"RANDOM": agent.NewRandomAgent(),
        "AggressiveAgent": team0.NewAggressiveAgent(),
        "CowardlyAgent": team0.NewCowardlyAgent(),
}
```

2022-11-23 21:43 UTC, sherwin-dc commented
> ```
> # in .env_team0
> MODE=default
> LEVELS=60
> STARTING_HP=1000
> STARTING_ATTACK=20
> STARTING_SHIELD=20
> BASE_STAMINA=2000
> THRESHOLD_PCT=0.6
> AGENT_RANDOM_QUANTITY=100
> AGENT_AggressiveAgent_QUANTITY=20
> AGENT_CowardlyAgent_QUANTITY=20
> ```
> 
> ```go
> // in team0_agent.go
> func NewAggressiveAgent() = NewProbabilisticAgent(0.1, 0.8, 0.1)
> func NewCowardlyAgent() = NewProbabilisticAgent(0.9, 0.05, 0.05)
> ```
> 
> ```go
> // in main.go
> var InitAgentMap = map[commons.ID]agent.Strategy{
> 	"RANDOM": agent.NewRandomAgent(),
>         "AggressiveAgent": team0.NewAggressiveAgent(),
>         "CowardlyAgent": team0.NewCowardlyAgent(),
> }
> ```

But this means each team would need to still write into the same agent map in main.go

2022-11-23 21:45 UTC, sherwin-dc commented
One of the purposes of my PR is to have teams define their own `var InitAgentMap = map[commons.ID]agent.Strategy{ ... }` within their files for their experiments

2022-11-23 22:00 UTC, 0x6770 commented
But this means every time other teams add new agent, you will need to modify that map if you want to include that new agent in your run.

2022-11-23 22:06 UTC, Razvan00Rusu commented
I havent had the time to look over this pr properly yet - but ill get home soon so can do then. 

But just from the conversation here I think it does make sense to move the agent map to agent teams as (I presume) proposed and maybe selected via a flag to avoid conflicts in main.go when teams merge their code in

2022-11-23 22:29 UTC, sherwin-dc commented
> But just from the conversation here I think it does make sense to move the agent map to agent teams as (I presume) proposed and maybe selected via a flag to avoid conflicts in main.go when teams merge their code in

Yes this, though I intended it for team experiments. It should be straightforward to extend this to combine the maps defined in multiple files so that teams can write their own maps even for normal gameplay against other teams.

> But this means every time other teams add new agent, you will need to modify that map if you want to include that new agent in your run.

This is intended for private team experiments where runs only have agents from one specific team. In this PR the `var InitAgentMap = map[commons.ID]agent.Strategy{ ... }` in main.go is still preserved and functions the same way (though we could follow @Razvan00Rusu's suggestion to also split it up if its desirable).

2022-11-24 12:50 UTC, Razvan00Rusu requested changes
A small typo in 2 of the files but other than that looks good to me

2022-11-24 12:50 UTC, Razvan00Rusu commented on pkg/infra/game/stage/initialise/initialise.go
> +func InitAgents(defaultStratergyMap map[commons.ID]agent.Strategy, gameConfig config.GameConfig) (numAgents uint, agentMap map[commons.ID]agent.Agent, agentStateMap map[commons.ID]state.AgentState) {
```suggestion
func InitAgents(defaultStrategyMap map[commons.ID]agent.Strategy, gameConfig config.GameConfig) (numAgents uint, agentMap map[commons.ID]agent.Agent, agentStateMap map[commons.ID]state.AgentState) {
```

2022-11-24 12:50 UTC, Razvan00Rusu commented on pkg/infra/game/stage/initialise/initialise.go
> +	for agentName, strategy := range defaultStratergyMap {
```suggestion
	for agentName, strategy := range defaultStrategyMap {
```

2022-11-24 12:50 UTC, Razvan00Rusu commented on pkg/infra/game/stages/stages.go
> +func ChooseDefaultStratergyMap(defaultStratergyMap map[commons.ID]agent.Strategy) map[commons.ID]agent.Strategy {
```suggestion
func ChooseDefaultStratergyMap(defaultStrategyMap map[commons.ID]agent.Strategy) map[commons.ID]agent.Strategy {
```

2022-11-24 12:50 UTC, Razvan00Rusu commented on pkg/infra/game/stages/stages.go
> +		return defaultStratergyMap
```suggestion
		return defaultStrategyMap
```

2022-11-24 13:40 UTC, Razvan00Rusu approved these changes

2022-11-24 14:48 UTC, sherwin-dc commented
Should we wait for any more comments or is it ready to merge in?

2022-11-24 14:54 UTC, Razvan00Rusu commented
> Should we wait for any more comments or is it ready to merge in?

Merge merge  mergeeee

2022-11-24 14:55 UTC, merged