Team1 agent metadata
SOMAS2022/SOMAS2022 pull request #73
Opened 2022-11-25 17:12 UTC by sherwin-dc

Copied same code in #66 into team1 files for experimentation.

Changed agent implementation to support new agent format

Need help with using the new `immutable.Map[commons.ID, HiddenAgentState]` in the agent

2022-12-03 18:15 UTC, sherwin-dc commented
@neeldug I think I'll need your help with `infra/teams/team1/utils/comms.go:33:36` where the interface implementation of Message is not being detected. I am  not sure what I am missing in order to make it work

2022-12-03 19:01 UTC, neeldug commented
> @neeldug I think I'll need your help with `infra/teams/team1/utils/comms.go:33:36` where the interface implementation of Message is not being detected. I am not sure what I am missing in order to make it work

Yes, this makes sense since messages must be implemented for all agents and cannot be implemented "per agent", instead it should be done within the `message` package.

2022-12-03 19:04 UTC, neeldug commented
> Yes, this makes sense since messages must be implemented for all agents and cannot be implemented "per agent", instead it should be done within the `message` package.

Moreover with #104 hopefully being merged soon, this should make the type system far stricter and ensure specific types of messages are implemented. But essentially implementing message types per-agent shouldn't be possible since the common language needs to be universal

2022-12-03 22:37 UTC, sherwin-dc commented
> Moreover with #104 hopefully being merged soon, this should make the type system far stricter and ensure specific types of messages are implemented. But essentially implementing message types per-agent shouldn't be possible since the common language needs to be universal

For our experiment we were planning on having agents send each other messages to share information, so I was looking at creating a message type just for a team experiment.

I can look into doing so, but in the meantime, how would I fill out the `HandleFightRequest` function to create a `message.FightInform` type? I should be able to go from there.
```go
func (r *RandomAgent) HandleFightRequest(_ message.TaggedMessage, _ *immutable.Map[commons.ID, decision.FightAction]) message.FightInform {
	return nil
}
```

2022-12-03 22:42 UTC, neeldug commented
> > Moreover with #104 hopefully being merged soon, this should make the type system far stricter and ensure specific types of messages are implemented. But essentially implementing message types per-agent shouldn't be possible since the common language needs to be universal
> 
> For our experiment we were planning on having agents send each other messages to share information, so I was looking at creating a message type just for a team experiment.
> 
> I can look into doing so, but in the meantime, how would I fill out the `HandleFightRequest` function to create a `message.FightInform` type? I should be able to go from there.
> 
> ```go
> func (r *RandomAgent) HandleFightRequest(_ message.TaggedMessage, _ *immutable.Map[commons.ID, decision.FightAction]) message.FightInform {
> 	return nil
> }
> ```

I think you ought to rebase once again, we've changed it a little but now you can see what the server sends as its message and it ought to be identical.

2022-12-04 17:49 UTC, neeldug requested changes

2022-12-04 17:49 UTC, neeldug commented on pkg/infra/game/message/message.go
> +type ArrayInfo struct {
Could this be moved into a separate file within the same package or even a sub-package just to keep things tidy?

2022-12-04 23:12 UTC, neeldug commented on pkg/infra/game/message/peer2peer.go
> +package message
Could you rename this file to `peer.go`, seems unnecessary to have numbers here.

2022-12-16 14:40 UTC, closed without merging