Extend messaging to hp pool and loot allocation
SOMAS2022/SOMAS2022 pull request #76
Opened 2022-11-28 02:57 UTC by Noanan

From Issue #57

2022-11-28 12:39 UTC, Noanan commented
Tried using generics but as mentionned in issue but this creates problems with our types (fight action is int which is comparable, but not the others)

2022-11-28 15:54 UTC, neeldug requested changes

2022-11-28 15:54 UTC, neeldug commented on pkg/infra/game/agent/agent.go
> +	CurrentLootDescion() decision.LootDecision
```suggestion
	CurrentLootDecision() decision.LootDecision
```

2022-12-02 19:48 UTC, Razvan00Rusu commented
This PR is a bit toooooo out of date. Please make a new one with the changes required.

2022-12-02 19:48 UTC, closed without merging